---
- name: Check if IUS repo is already configured
  stat:
    path: /etc/yum.repos.d/ius.repo
  register: ius_repofile_result

- name: Configure IUS variables
  set_fact:
    ius_distribution_abbrev: "{{ (ansible_distribution == 'CentOS') | ternary('centos', 'rhel') }}"

- name: Install IUS repo
  yum:
    name: |
      https://{{ ius_distribution_abbrev }}{{ ansible_distribution_major_version }}.iuscommunity.org/ius-release.rpm
    state: present
  when: not ius_repofile_result.stat.exists

- name: Import IUS GPG key
  rpm_key:
    key: /etc/pki/rpm-gpg/IUS-COMMUNITY-GPG-KEY
    state: present
  when: not ius_repofile_result.stat.exists
